# Generated by Django 4.2.7 on 2025-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteapp', '0004_entreprisesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprisesettings',
            name='nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
