# Generated by Django 4.2.7 on 2025-06-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteapp', '0005_alter_entreprisesettings_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
